---
- hosts: all

  tasks:
    - name: Update SUSE servers
      zypper:
            name: '*'
            state: latest
            type: patch

    - name: Reboot SUSE servers after applying patches
      reboot:
              msg: "Reboot initiated by Ansible for updates"
              connect_timeout: 5
              reboot_timeout: 300
              pre_reboot_delay: 0
              post_reboot_delay: 30
              test_command: uptime