---
- hosts: all
  tasks:
    - name: Create a snapshot
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "/{{ datacenter_name }}/vm/"
        name: "{{ guest_name }}"
        state: present
        snapshot_name: Snap_patching
        description: Snap patching
      delegate_to: localhost
